# Archivo que le dice a travis que hacer cada vez que se produce un cambio en nuestro proyecto
language: python
python:
  - "3.6"

services:
 - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
